TASK1:
  name: VQA
  type: VL-classifier
  num_labels: 3129
  loss: BCEWithLogitLoss
  process: normal
  task_id: 1
  dataroot: datasets/vqa/annotations
  features_h5path1: datasets/mscoco/resnet101_faster_rcnn_genome_imgfeats/volta/trainval_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 20
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 1024
  train_split: train
  val_split: val
  lr: 0.00005
  num_epoch: 20
TASK12:
  name: NLVR2
  type: VL-binary-classifier
  num_labels: 2
  loss: BCEWithLogitLoss
  process: nlvr
  task_id: 12
  dataroot: datasets/nlvr2/annotations
  features_h5path1: datasets/nlvr2/resnet101_faster_rcnn_genome_imgfeats/volta/nlvr2_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 20
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 512
  train_split: train
  val_split: dev
  lr: 0.00005
  num_epoch: 20
TASK15:
  name: GQA
  type: VL-classifier-GQA
  num_labels: 1842
  loss: BCEWithLogitLoss
  process: normal
  task_id: 15
  dataroot: datasets/gqa/annotations
  features_h5path1: datasets/gqa/resnet101_faster_rcnn_genome_imgfeats/volta/vg_gqa_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 20
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 1024
  train_split: train
  val_split: val
  lr: 0.00001
  num_epoch: 20
