TASK1:
  name: VQA
  type: VL-classifier
  num_labels: 3129
  loss: BCEWithLogitLoss
  process: normal
  task_id: 1
  dataroot: datasets/vqa/annotations
  features_h5path1: datasets/mscoco/resnet101_faster_rcnn_genome_imgfeats/volta/trainval_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 23
  max_region_num: 36
  batch_size: 256
  eval_batch_size: 1024
  train_split: train
  val_split: val
  lr: 0.0001
  num_epoch: 20
  fusion_method: vl-bert_vqa
  embed_clf: true
TASK10:
  name: refcoco+
  type: V-logit
  loss: BCEWithLogitLoss
  process: normal
  task_id: 10
  dataroot: datasets/refcoco+_unc/annotations
  features_h5path1: datasets/refcoco+_unc/resnet101_faster_rcnn_genome_imgfeats/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 30
  max_region_num: 36
  batch_size: 256
  eval_batch_size: 1024
  train_split: train
  val_split: val
  lr: 0.0001
  num_epoch: 20
  num_clf_layers: 2
